### ISSUE TITLE
Flint failed to find Readme.md

### ISSUE THREAD

**Issue by andrewhood125** [pengwynn/flint#11]
Would you be open to making flint case insensitive? https://github.com/pengwynn/flint/blame/master/flint/flint.go#L18-L22

**Comment by kruug** [comment]
This still has not been merged.  It's also failing to find "license" as I can only assume it's searching for "LICENSE".

**Comment by andrewhood125** [comment]
:cry:

**Comment by pengwynn** [comment]
Patches are welcome. :grinning:

**Comment by kruug** [comment]
Looks like NathanielChanning forked and patched, just never submitted a pull request.
