### ISSUE TITLE
github_fetcher arguments error

### ISSUE THREAD

**Issue by kruug** [pengwynn/flint#22]
kruug@kruugdeb:~ $ go get github.com/pengwynn/flint
\# github.com/pengwynn/flint/flint
dev/go/src/github.com/pengwynn/flint/flint/github_fetcher.go:27: too many arguments in call to g.Client.Repositories
dev/go/src/github.com/pengwynn/flint/flint/github_fetcher.go:27: not enough arguments in call to g.Client.Repositories(url).One
kruug@kruugdeb:~ $ flint --version
-bash: flint: command not found

Not sure how to fix.

**Comment by k2b6s9j** [comment]
I am also having this issue with a fresh install of Go on OS X Yosemite.

**Comment by k2b6s9j** [comment]
I was really hoping to integrate this into Atom tonight too!

**Comment by pengwynn** [comment]
Should be fixed by c3a5d8d.
