### ISSUE TITLE
Atom Integration

### ISSUE THREAD

**Issue by k2b6s9j** [pengwynn/flint#33]
I've created an Atom package that integrates with the Linter package to show issues. Though you might like to check it out. https://atom.io/packages/linter-flint

**Comment by pengwynn** [comment]
Oh nice! Thanks for sharing. :zap:

I wrote flint in Go mostly to learn how to build a CLI app in Go. For the Atom package, have you thought about porting flint to Coffee to avoid the Go lib dependency? If you do, let me know. I'd love to follow along.
