### ISSUE TITLE
Go vendoring?

### ISSUE THREAD

**Issue by ilovezfs** [pengwynn/flint#46]
`flint-checker` was just added as a new formula in Homebrew in https://github.com/Homebrew/homebrew-core/pull/12701. The formula has six `go_resource` blocks.

Would you be willing to start using the Go vendor directory or one of the other Go vendor systems so that we can remove these resource blocks?

**Comment by pengwynn** [comment]
Sure thing. Fixed in #47.

**Comment by ilovezfs** [comment]
@pengwynn thank you! Would you be willing to create a new tag so we can get that integrated into the formula?

**Comment by pengwynn** [comment]
@ilovezfs yup, just pushed v0.1.0 👍
